version: '2'
services:
  web:
    image: gcr.io/project-aviron/hapimongo:0.1
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      MONGO_HOST: mongo
  mongo:
    image: gcr.io/project-aviron/mongodb:0.1
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
