apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongodb
    spec:
    #  nodeSelector:
    #   cloud.google.com/gke-nodepool: db-pool
     containers:
       - image: gcr.io/project-aviron/mongodb:0.1
         name: mongodb
         imagePullPolicy: IfNotPresent

         ports:
           - containerPort: 27017
    #      volumeMounts:
    #        - name: mongo-disk
    #          mountPath: /data/db
    #  volumes:
    #    - name: mongo-disk
    #      gcePersistentDisk:
    #        pdName: db-disk
    #        fsType: ext4
